name: ESLint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.8.0
        with:
          useLockFile: true
          useCache: false

      - name: Run ESLint
        run: |
          npx eslint src/
