name: ESLint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint src/
